### ISSUE TITLE
Reporting Lint result fails

### ISSUE THREAD

**Issue by sascha-egerer** [uber-archive/phabricator-jenkins-plugin#255]
Lint results are not reported to phabricator. 

The lint results are successfully written to a file and also read by the plugin.

Content of the Lint file:
```
{"Makefile":[{"line":9,"char":1,"code":"TXT2","severity":"error","name":"Tab Literal","description":"Configure your editor to use spaces for indentation.","original":"\t","replacement":null,"granularity":1,"locations":[],"bypassChangedLineFiltering":null,"context":"ARGUMENTS=$(filter-out $@,$(MAKECMDGOALS))\n\nhelp: ## Show this help\n\t$(info Available targets)\n\t@awk '\/^[a-zA-Z\\-\\_0-9]+:\/ { \\\n\t\tnb = sub( \/^## \/, \"\", helpMsg ); \\\n\t\tif(nb == 0) { \\"}]}
```

Jenkins logs:
```
[phabricator:plugin-provider] 'cobertura' plugin not installed.
[phabricator:process-build-result] No unit results available.
[phabricator:process-build-result] No coverage provider available.
[phabricator:harbormaster] Sending Harbormaster BUILD_URL via PHID: PHID-HMBT-XXXX
[phabricator:process-build-result] Publishing lint results for 1 violations
[phabricator:process-build-result] Sending build result to Harbormaster with PHID PHID-HMBT-XXXX, success: false
[phabricator:send-harbormaster-result] Error from Harbormaster: Missing required parameters: name, code, severity, path
[phabricator:send-harbormaster-result] Unable to post to Harbormaster
[phabricator:send-harbormaster-result] Error sending Harbormaster unit results, trying again without unit data (you may have an old Phabricator?).
[phabricator:file-fetcher] no file configured
```
So the plugin has found one violation in the file which is correct. 

I've just debugged what phabricator receives and it is an empty lint result.
The POST sent to phabricator contains this body
```
{"params":"{\"type\":\"fail\",\"buildTargetPHID\":\"PHID-HMBT-XXX\",\"lint\":[{}],\"__conduit__\":{\"token\":\"api-XXX\"}}"}
```
So the lint result is getting lost somewhere in the plugin between https://github.com/uber/phabricator-jenkins-plugin/blob/93043b1ab74406c537490d96e1ffa4290585ceb8/src/main/java/com/uber/jenkins/phabricator/BuildResultProcessor.java#L229
and 
https://github.com/uber/phabricator-jenkins-plugin/blob/93043b1ab74406c537490d96e1ffa4290585ceb8/src/main/java/com/uber/jenkins/phabricator/tasks/SendHarbormasterResultTask.java#L57

**Comment by sascha-egerer** [comment]
Nobody with the same problem? Could somebody help me to find the cause of the problem? Maybe just something wrong in the configuration?

**Comment by sascha-egerer** [comment]
As far as i can see that can't work. At least not with the "--output json" result of the latest arcanist version.
How does the expected `arc lint` output look like? Looks like the expected format is totally different from what i posted above.

**Comment by douardda** [comment]
For what I have understood, the phabricator-jenkins-plugin builds a [harbormaster.sendmessage](https://secure.phabricator.com/conduit/method/harbormaster.sendmessage) collecting unit test results (not sure how that works too) and reading the lint part  from the phabricator-lint file (by default), which should be formatted as you describe (and NOT like "arc lint --outout json" seems to generates).

I'd like to see the exact HTTP request (Conduit) made by the plugin when it sends this message, but I'm not sure how to do so.

BTW I have the same problem ;-)

**Comment by sascha-egerer** [comment]
Give me some minutes, i'll prepare a pull request for this issue

**Comment by sascha-egerer** [comment]
@douardda Could you please test my pull requests. Attached is also a compiled version including the change (you have to unzip the file and then upload the hpi file to jenkins)
[phabricator-plugin.hpi.gz](https://github.com/uber/phabricator-jenkins-plugin/files/2514626/phabricator-plugin.hpi.gz)

**Comment by douardda** [comment]
@sascha-egerer 

I have the following error:

```
java.lang.ClassCastException: java.lang.String cannot be cast to net.sf.json.JSONArray
	at com.uber.jenkins.phabricator.BuildResultProcessor.processLintResults(BuildResultProcessor.java:170)
	at com.uber.jenkins.phabricator.PhabricatorNotifier.perform(PhabricatorNotifier.java:269)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1844)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Post to Phabricator' marked build as failure
```

with .phabricator-lint being:

```
{"context": "def some_stuff(toto):\n", "name": "flake8", "description": "expected 2 blank lines, found 1", "code": "E302", "char": 1, "severity": "error", "path": "sandbox/__init__.py", "line": 3}
{"context": "  print ('with flake8 errors')\n", "name": "flake8", "description": "too many blank lines (2)", "code": "E303", "char": 3, "severity": "error", "path": "sandbox/__init__.py", "line": 6}
{"context": "  print ('with flake8 errors')\n", "name": "flake8", "description": "indentation is not a multiple of four", "code": "E111", "char": 3, "severity": "error", "path": "sandbox/__init__.py", "line": 6}
{"context": "  print ('with flake8 errors')\n", "name": "flake8", "description": "whitespace before '('", "code": "E211", "char": 8, "severity": "error", "path": "sandbox/__init__.py", "line": 6}
{"context": "  toto = 42\n", "name": "flake8", "description": "indentation is not a multiple of four", "code": "E111", "char": 3, "severity": "error", "path": "sandbox/__init__.py", "line": 7}
{"context": "  toto = 42\n", "name": "flake8", "description": "local variable 'toto' is assigned to but never used", "code": "F841", "char": 3, "severity": "advice", "path": "sandbox/__init__.py", "line": 7}
{"context": "  \n", "name": "flake8", "description": "blank line contains whitespace", "code": "W293", "char": 1, "severity": "warning", "path": "sandbox/__init__.py", "line": 8}
```
What is the expected format with your PR?

**Comment by sascha-egerer** [comment]
Ok that is not the format i do expect. 
I use the format provided by `arc lint --output json`. But looks like i'm the only one doing this?! 
How do you create the lint file?

The format is like:
```
{"sandbox/__init__.py":[{"context": "  print ('with flake8 errors')\n", "name": "flake8", "description": "too many blank lines (2)", "code": "E303", "char": 3, "severity": "error", "line": 6},{"context": "  print ('with flake8 errors')\n", "name": "flake8", "description": "indentation is not a multiple of four", "code": "E111", "char": 3, "severity": "error", "line": 6}]";
```

**Comment by douardda** [comment]
I wrote a small flake8 plugin to generate phabricator-compliant file on 
  https://framagit.org/douardda/flake8-phabricator-formatter

At first I did implement it to output a json file similar to what `arc lint --output json` does, but the I saw in  the ['advanced' documentation](https://github.com/uber/phabricator-jenkins-plugin/blob/master/docs/advanced.md#custom-lint) of the phabricator-jenkins-plugin that the expected format is a non-JSON file containing JSON dictionnaries:

> Although each line must be valid JSON, note that the file as a whole is not valid JSON (e.g. if you call JSON.parse('.phabricator-lint')) it will fail. This is a design decision to make it easy for build scripts to tee (echo line-by-line) violations without having to produce well-formed JSON, which requires knowing upfront how many violations are present.

So I changed my flake8 plugin to that format.

However, even with that format, even if the logs of the phabricator plugin state that lint statements are properly loaded, these are not visible on phabricator (in the Diff view foor example, if the jenkins job is started by an herald hook on Diff updates). Which is I believe what you describe in your issue.


Whatever, the fact that `arc lint` cannot produce an output file compatible with this phabricator-jenkins-plugin is, at best, unfortunate. But I think I understand why it is that way.

**Comment by douardda** [comment]
Ok, I've reverted back to original  phabricator-jenkins-plugin v 2.0.1 and my latest attempt did correctly upload the link statements!

![screenshot_2018-10-29 d585 test stuff no need for review](https://user-images.githubusercontent.com/1496354/47664344-26151900-db9f-11e8-9347-ec69d3877914.png)

**Comment by hchow77** [comment]
I just ran into this issue as well after following the instructions in the [Advance Usage](https://github.com/uber/phabricator-jenkins-plugin/blob/master/docs/advanced.md) doc. Sounds like there was some success by reverting to v2.0.1 of the plugin (currently on 2.1.1), but wanted to check here before I started rolling things back to see if there's been any luck with what's current.

I can confirm I was using the harbormaster "each line is JSON" format, which I was able to get the plugin to recogonize 2 distinct entries (Logged "Publishing lint results for 2 violations"), and I'm testing this in parallel with a comment file, which seems to be working fine so there shouldn't be an issue with the pipe between jenkins and phab. I just don't see any update in phabricator for my linter output.

@sascha-egerer btw, how did you debug the POST to phabricator? I'm no networking, jenkins, or phabricator expert so any help there would be appreciated!

**Comment by sascha-egerer** [comment]
> @sascha-egerer btw, how did you debug the POST to phabricator? I'm no networking, jenkins, or phabricator expert so any help there would be appreciated!

@hchow77 Sorry for the late feedback. I've added some debug statements to the Java Code, compiled the Jenkins plugin and used that version. Don't know if there is a better possibility.

**Comment by hchow77** [comment]
> @hchow77 Sorry for the late feedback. I've added some debug statements to the Java Code, compiled the Jenkins plugin and used that version. Don't know if there is a better possibility.

No problem about the delay. Just thankful for a response! That thought had occurred to me but was hoping I wouldn't have to resort to that, but at least from the sounds of it, there might be a bug in the linter reporting code. Guess I'll either have to wait for a fix or if I find some time I'll have to try fixing it myself.

Thanks again for the reply @sascha-egerer

**Comment by hchow77** [comment]
Huh, randomly checked out my test revision today, and suddenly I have the inline comments showing from lint results. Not sure what changed, but seems like stuff is working. Perhaps there was a delay or maybe I unknowingly modified the format to something that worked, but for now looks like the bug was a non-bug. Will come back here if I have further issues but for now I'm assuming I'm good :)

**Comment by wraitii** [comment]
Ran into this issue with the latest version. I queried on arcanist - the format is unlikely to be updated.
As a workaround, I've written an arcanist extension that outputs listing results for this plugin with `--output jenkins`, see https://code.wildfiregames.com/source/0ad/browse/ps/trunk/build/arclint/pyrolint/src/JenkinsRenderer.php
Additionally, the following jq command works on `--output json`:
```jq -c '[to_entries][0][0] | .key as $key | .value[] + { "path": $key }'```
